acmeair-nginx1:
    container_name: acmeair-nginx1
    net: ${NETWORK}
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /www/public
    volumes_from:
      - acmeair-mainservice-java
      - acmeair-authservice-java
      - acmeair-bookingservice-java
      - acmeair-customerservice-java
      - acmeair-flightservice-java
  
  acmeair-mainservice-java:
    container_name: acmeair-mainservice-java
    dockerfile: Dockerfile-daily
    net: ${NETWORK}
    build: ../acmeair-mainservice-java/
    environment:
      - LICENSE=accept
  
  acmeair-authservice-java:
    container_name: acmeair-authservice-java
    dockerfile: Dockerfile-daily
    net: ${NETWORK}
    build: ../acmeair-authservice-java/
    environment:
      - LICENSE=accept
  
  acmeair-bookingservice-java:
    container_name: acmeair-bookingservice-java
    dockerfile: Dockerfile-daily
    net: ${NETWORK}
    build: ../acmeair-bookingservice-java/
    environment:
      - LICENSE=accept
      - MONGO_HOST=10.0.0.82
  
  acmeair-customerservice-java:
    container_name: acmeair-customerservice-java
    dockerfile: Dockerfile-daily
    net: ${NETWORK}
    build: ../acmeair-customerservice-java/
    environment:
      - LICENSE=accept
      - MONGO_HOST=10.0.0.82
  
  acmeair-flightservice-java:
    container_name: acmeair-flightservice-java
    dockerfile: Dockerfile-daily
    net: ${NETWORK}
    build: ../acmeair-flightservice-java/
    environment:
      - LICENSE=accept
      - MONGO_HOST=10.0.0.82
